### ISSUE TITLE
Error when using where condition for has_one, rails 4.1+

### ISSUE THREAD

**Issue by deemkey** [vovayartsev/dase#4]
ArgumentError: wrong number of arguments (given 2, expected 1)
/dase-4.1.1/lib/dase/mp_active_record.rb:28:in `merge'

has_one :owner, -> {where some_column: 'value'}, class_name: 'Class'

**Comment by vovayartsev** [comment]
Appeared to be a conflict with Squeel gem. Fixed in dase-4.2.1.
